format = """
[](bg:#272822 fg:#f92672)\
$username\
[](bg:#fd971f fg:#272822)\
$hostname\
[](bg:#a6e22e fg:#fd971f)\
$directory\
[](bg:#66d9ef fg:#a6e22e)\
$time\
[](fg:#66d9ef)\
$character"""

right_format = """$cmd_duration"""

[username]
style_user = "bg:#272822 fg:#f92672"
style_root = "bg:#272822 fg:#f92672"
format = "[ $user ]($style)"
show_always = true

[hostname]
style = "bg:#fd971f fg:#272822"
format = "[ $hostname ]($style)"
ssh_only = false

[directory]
style = "bg:#a6e22e fg:#272822"
format = "[ $path ]($style)"
truncation_length = 3
truncate_to_repo = true

[time]
disabled = false
time_format = "%H:%M"
style = "bg:#66d9ef fg:#272822"
format = "[ $time ]($style)"

[cmd_duration]
min_time = 500
format = "[$duration](bold #e6db74)"

[character]
success_symbol = "[❯](bold #ae81ff)"
error_symbol = "[❯](bold #f92672)"
vimcmd_symbol = "[❮](bold #a6e22e)"