# Sunshine Configuration

# General
min_log_level = info
sunshine_name = XGW

# Network
port = 47989
upnp = disabled
origin_web_ui_allowed = lan
external_ip =

# Audio/Video
adapter_name = /dev/dri/renderD128
output_name =
max_bitrate = 50000
encoder = vaapi

# HEVC/AV1
hevc_mode = 0
av1_mode = 0

# Software Encoding
# encoder = software

# Video Quality
qp = 23

# Input
gamepad = auto
